version: '2'

services:
  goproxy:
    container_name: go-proxy
    restart: always
    image: jsimonetti/goproxy:latest
    #    ports:
    #      - 8880:8080
    volumes:
      - ./cache:/cache
    networks:
      goproxy:
        ipv4_address: 10.12.0.2

networks:
  goproxy:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.name: "goproxy0"
    ipam:
      config:
        - subnet: 10.12.0.0/24
          gateway: 10.12.0.1

